### ISSUE TITLE
Closing the alert doesn't instantly stop the alarm.

### ISSUE THREAD

**Issue by theonlygusti** [theonlygusti/alarm#11]
Closing the alert should stop the alarm.

At the moment however, the alarm plays through the remainder of the sound before cutting out.

**Comment by theonlygusti** [comment]
```
>>> run(1.0, "1 second alarm")
button returned:OK
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "plugin.py", line 142, in run
    alert_after_timeout(seconds, message)
  File "plugin.py", line 99, in alert_after_timeout
    thread.stop()
  File "plugin.py", line 89, in stop
    self.process.kill()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1564, in kill
    self.send_signal(signal.SIGKILL)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1554, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process
```

**Comment by theonlygusti** [comment]
[Asked on stackoverflow](http://stackoverflow.com/questions/41410264/class-attribute-doesnt-get-assigned-correctly)

**Comment by theonlygusti** [comment]
Traceback (most recent call last):
      File "test.py", line 28, in <module>
        thread.stop()
      File "test.py", line 21, in stop
        self.process.kill()
    AttributeError: 'AlarmThread' object has no attribute 'process'

I don't really know why this error would get thrown, but it looks like `self.process` is, for some reason, not assigned when `AlarmThread.stop` is called.

This makes no sense to me, as from my code it looks like `thread.stop` is only called after `thread.start`:

    import subprocess
    import threading

    class AlarmThread(threading.Thread):
        def __init__(self, file_name="beep.wav"):
            super(AlarmThread, self).__init__()
            self.file_name = file_name
            self.ongoing = None
    
        def run(self):
            self.ongoing = True
            while self.ongoing:
                self.process = subprocess.Popen(["afplay", self.file_name])
                self.process.wait()
    
        def stop(self):
            if self.ongoing is not None:
                self.ongoing = False
                self.process.kill()

    thread = AlarmThread()
    thread.start()
    # show_alert is synchronous, an alert must be closed before the script continues
    show_alert("1 second timer")

    thread.stop()
    thread.join()
