### ISSUE TITLE
error causes plugin to not work at all

### ISSUE THREAD

**Issue by theonlygusti** [theonlygusti/alarm#20]
Since 37abc122c19f38974555b287285c707bb650966d

**Comment by theonlygusti** [comment]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "plugin.py", line 165, in results
    seconds = parse_time_span(time)
TypeError: parse_time_span() takes exactly 2 arguments (1 given)
```

**Comment by theonlygusti** [comment]
Fixed previous error.

Now:


```
>>> results({ "~arguments": "2.5s" }, "alarm in 2.5s")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "plugin.py", line 165, in results
    seconds = parse_time_span(time, time_span_pattern)
  File "plugin.py", line 49, in parse_time_span
    seconds = 0 if seconds is None else int(seconds)
ValueError: invalid literal for int() with base 10: '2.5'
```
