### ISSUE TITLE
alarm doesn't get triggered

### ISSUE THREAD

**Issue by theonlygusti** [theonlygusti/alarm#9]
since f277d462dd4691db70f139a055964a3790f2cfd1

**Comment by theonlygusti** [comment]
This is really weird because all the individual functions do what they are meant to do:

```
>>> results({"~arguments":"1s"}, "1s")
{'run_args': [1, '1 second alarm'], 'webview_transparent_background': True, 'title': 'Alarm in 1 second', 'html': '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title></title>\n</head>\n<body>\n  <center>\n    <iframe src="http://free.timeanddate.com/clock/i5incat5/n136/szw110/szh110/hbw0/hfc000/cf100/hgr0/fav0/fiv0/mqcfff/mql15/mqw4/mqd94/mhcfff/mhl15/mhw4/mhd94/mmv0/hhcbbb/hmcddd/hsceee" frameborder="0" width="110" height="110"></iframe>\n  </center>\n</body>\n</html>\n'}
>>> run(1, "1 second alarm")
button returned:OK
```

**Comment by theonlygusti** [comment]
Ok I am narrowing down the problem.

```
$ py2 -i plugin.py
>>> results({"~arguments":"1s"}, "alarm in 1s")
{'webview_transparent_background': True, 'html': '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title></title>\n</head>\n<body>\n  <center>\n    <iframe src="http://free.timeanddate.com/clock/i5incat5/n136/szw110/szh110/hbw0/hfc000/cf100/hgr0/fav0/fiv0/mqcfff/mql15/mqw4/mqd94/mhcfff/mhl15/mhw4/mhd94/mmv0/hhcbbb/hmcddd/hsceee" frameborder="0" width="110" height="110"></iframe>\n  </center>\n</body>\n</html>\n', 'run_args': [1.0, '1 second alarm'], 'title': 'Alarm in 1 second'}
>>> run(1.0, "1 seconds alarm")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "plugin.py", line 144, in run
    alert_after_timeout(seconds, message)
  File "plugin.py", line 96, in alert_after_timeout
    thread = AlarmThread()
  File "plugin.py", line 78, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
```
